version: '2'
services:
  db:
    image: postgres
    volumes:
      - blogdata:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=www.pogona.org,pogona.org,www.pogonareport.com,pogonareport.com
    volumes:
      - ./:/src
      - ./config/nginx:/etc/nginx/conf.d
      # - ./ssl:/etc/ssl/
      - ./etc/live/www.pogonareport.com:/etc/ssl/
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    expose:
      - "80"
    depends_on:
      - db

volumes:
  blogdata:
    external: true
