# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170525_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(default='Anonymous', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.BlogPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
