# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpagecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecomments',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
