# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170525_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'blog comments',
            },
        ),
        migrations.RemoveField(
            model_name='blogpagecomments',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogPageComments',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='comments',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogComment'),
        ),
    ]
