# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogpagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagecomment',
            name='post_as_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
