# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogpagecomment_post_as_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagecomment',
            options={'ordering': ['approved', '-created']},
        ),
    ]
