# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170526_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpagecomment',
            name='name',
            field=models.CharField(blank=True, help_text='optional', max_length=255),
        ),
    ]
