# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170526_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecomment',
            name='name',
            field=models.CharField(blank=True, help_text='(optional)', max_length=255),
        ),
    ]
