# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 00:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170612_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='motto',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
