# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170627_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='motto',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
